services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-dev
    volumes:
      - ./backend:/app
      - /app/vendor
    ports:
      - "8000:8000"
    environment:
      DB_BACKEND_USER: backend
      DB_BACKEND_PASSWORD: backend
      DB_BACKEND_NAME: backend_db
      DB_BACKEND_HOST: backend_db
      DB_BACKEND_PORT: 5432
    depends_on:
      - backend_db


  frontend:
    build: ./frontend
    container_name: frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  mobile:
    build: ./mobile
    container_name: mobile-dev
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./mobile:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      EXPO_DEV_SERVER_PORT: 19000
      EXPO_DEV_SERVER_HOST: 0.0.0.0
    command: >
      sh -c "npx expo start --tunnel --port 19000 --dev-client"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus/

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    depends_on:
      - sonar_db

  # PostgreSQL pour SonarQube
  sonar_db:
    image: postgres:18
    container_name: sonar-db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - sonarqube_db:/var/lib/postgresql/

  # PostgreSQL pour le backend
  backend_db:
    image: postgres:18
    container_name: backend-db
    environment:
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: backend
      POSTGRES_DB: backend_db
    ports:
      - "5433:5432"
    volumes:
      - backend_db_data:/var/lib/postgresql/

volumes:
  grafana-data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_db:
  backend_db_data: